version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "mariobehling"
    groups:
      frontend:
        patterns:
          - "react"
          - "react-dom"
          - "react-grid-layout"
          - "react-resize-detector"
          - "react-modal"
          - "react-devtools"
          - "d3-*"
          - "three"
          - "jquery"
        update-types: ["minor", "patch"]
      devdeps:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "mariobehling"
